services:
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:26.0.5
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8087:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev